---
- name: This playbook is used for Jenkins pipeline
  hosts: all
  become: true
  vars_files:
    - user-pass.txt
  tasks:
    - name: Adding some users and given passwords
      ansible.builtin.user:
        name: "{{ item.username }}"
        password: "{{ item.password }}"
        state: absent
        update_password: on_create
      loop: "{{ users }}"

    # - name: Change password on first login
    #   ansible.builtin.command:
    #     cmd: chage -d 0 "{{ item.username }}"
    #   register: my_output
    #   changed_when: my_output.rc == 0
    #   loop: "{{ users }}"

- name: Adding some services
  hosts: all
  become: true
  vars:
    packages:
      - httpd
      - mariadb
      - postgresql
      - chrony
      - vsftpd
  tasks:
    - name: Installing services on RHEL machine
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: absent
      loop: "{{ packages }}"
